apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo
    app_version: {{ .Values.image.old_version }}

---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo-new
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo
    app_version: {{ .Values.image.version }}
